// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Filename    string `gorm:"column:filename;type:varchar(128);not null" json:"filename"`
	UserID      int64  `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	PatientName string `gorm:"column:patient_name;type:varchar(64);not null" json:"patient_name"`
	PatientAge  int64  `gorm:"column:patient_age;type:int;not null" json:"patient_age"`
	CreateTime  int64  `gorm:"autoCreateTime" json:"create_time"`
	Status      string `gorm:"column:status;type:varchar(32);not null" json:"status"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
